### ISSUE TITLE
Cannot be imported as package

### ISSUE THREAD

**Issue by bjrne** [kermitt2/grobid_client_python#14]
Thanks for going through the trouble to also provide an asynchronous example client for grobid!

In order to use the code in existing python programs through import statements filenames must not contain dashes, as well as the folder/module name. It's actually only a tiny code change, so I have already pushed a PR for easier discussion. However, the repo itself would also need a renaming since its name also contains dashes.

**Comment by kermitt2** [comment]
Thank you @bjrne !

Indeed, as written [here](https://github.com/kermitt2/grobid-client-python/issues/8#issuecomment-620015674) the client is a bit half done ;)

I will go through the process you propose in the next days, thanks.

**Comment by kermitt2** [comment]
This is implemented by #26

**Comment by bjrne** [comment]
I haven't tested it again myself, but that sounds like this is ready to be closed :bee:
