### ISSUE TITLE
teiCoordinates not showing

### ISSUE THREAD

**Issue by xcrema** [kermitt2/grobid_client_python#22]
I want to get the coordinates for the pdf elements. I am running this command:

python3 grobid_client.py --input ~/tmp/in2 --output ~/tmp/out processHeaderDocument --force --teiCoordinates

But I am not getting the coordinates in created xml document. Can you help me where I am going wrong?

**Comment by kermitt2** [comment]
Hello hello

Currently coordinates are added only for the `processFulltextDocument` service (for `processHeaderDocument`, the parameter `teiCoordinates` is ignored).
