### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by samanyougarg** [kermitt2/grobid_client_python#27]
Hi, I have a server running and am trying to run the following code to extract text from 1 PDF but don't get any output files.

```
from grobid_client.grobid_client import GrobidClient

client = GrobidClient(config_path="./config.json")
client.process("processFulltextDocument", "article.pdf", n=1, force=True)
```

It just says "GROBID server is up and running" and stops.

**Comment by kermitt2** [comment]
Hello ! 

The `process()` method is expecting a path to a repository of PDF files, not an individual PDF. So no file to process found and nothing done (see https://github.com/kermitt2/grobid_client_python/blob/master/grobid_client.py#L91).

**Comment by samanyougarg** [comment]
Thank you very much!
