### ISSUE TITLE
ERROR: GROBID server does not appear up and running

### ISSUE THREAD

**Issue by walkyrie67** [kermitt2/grobid_client_python#33]
Hello,

I am trying to install the python version of Grobid and I have python 3.7.5 and linux machine
I have installed the project into a directory, and I am getting the following error after entering the CLI:
`grobid_client --input /home/laurent/Documents/test_file_ETL_DE_BE/test_grobid processFulltextDocument
``GROBID server does not appear up and running, the connection to the server failed
`
Any idea where the error is coming from? Thank you for your help.
Laurent

**Comment by kermitt2** [comment]
Hello !

You need a running GROBID server to use this client, see the documentation https://github.com/kermitt2/grobid-client-python#build-and-run

I recommend to use the docker image, which should be as simple as this:

```
docker pull lfoppiano/grobid:0.7.0
docker run -t --rm --init lfoppiano/grobid:0.7.0
```

**Comment by walkyrie67** [comment]
Oh nice, its indeed working! 

Thank you! 
Laurent

**Comment by Umar888** [comment]
@kermitt2 I followed your instructions but it still says Grobid server does not appear up and running

**Comment by kermitt2** [comment]
@Umar888 Hello ! We need more information on your os, environment, server version, etc. and on what you are exactly doing when installing the server to understand and reproduce a problem.

**Comment by Umar888** [comment]
@kermitt2  i am running on Mac OS Monterey(12.3). I am using jupyter notebook running on anaconda navigator
<img width="1140" alt="Screenshot 2022-04-22 at 12 31 36 PM" src="https://user-images.githubusercontent.com/44860615/164628261-4e459408-0d15-4913-b6f9-1faa1e0f87fb.png">
r

**Comment by Umar888** [comment]
@kermitt2  do u need any further any information?

**Comment by Umar888** [comment]
@kermitt2  do i need to run on. any other compiler? even in terminal it says server is running
<img width="570" alt="Screenshot 2022-04-22 at 12 39 29 PM" src="https://user-images.githubusercontent.com/44860615/164632358-965d3b44-1e56-4eff-84bf-bdc16145c22e.png">

**Comment by kermitt2** [comment]
Thank you @Umar888 

Could you do a simple curl request to see if the server is okay:

```
curl -X POST -d "citations=Graff, Expert. Opin. Ther. Targets (2002) 6(1): 103-113" localhost:8070/api/processCitation
```

If it works, it might be due to the  jupyter notebook environment. One basic thing  to testis to replace in `grobid_client_python/config.json` `localhost` by `0.0.0.0`.

**Comment by Umar888** [comment]
@kermitt2  it gives me this error now
![Uploading Screenshot 2022-04-22 at 1.02.58 PM.png…]()

**Comment by Umar888** [comment]
@kermitt2  it gives me this error now
<img width="576" alt="Screenshot 2022-04-22 at 1 02 58 PM" src="https://user-images.githubusercontent.com/44860615/164645206-afb731bc-1b88-452e-a3c6-056a855999a2.png">

**Comment by Umar888** [comment]
@kermitt2  it says failed to connect to localhost port 8070

**Comment by Umar888** [comment]
@kermitt2  can we have google meet session? I want to show you live how I am setting up things

**Comment by kermitt2** [comment]
@Umar888 usually this problem comes from the docker run, the port need to be mapped: 

```
docker run -t --rm --init -p 8070:8070 lfoppiano/grobid:0.7.1
```

see https://grobid.readthedocs.io/en/latest/Grobid-docker/#crf-only-image

**Comment by Umar888** [comment]
@kermitt2  brother I got this issue now. I need your suggestion regarding this
<img width="1440" alt="Screenshot 2022-04-25 at 1 02 04 PM" src="https://user-images.githubusercontent.com/44860615/165046223-8ece984b-be3f-4079-a78c-69c0b3356243.png">

**Comment by kermitt2** [comment]
@Umar888 It might be due to the `consolidate_citations=True`. Consolidation calls CrossRef REST service by default to match extracted references against DOI and this web service is not very reliable and does not scale well. I would try with `consolidate_citations=False` to see if the timeout error disappears. If it's the case, you can then decrease the concurrency of the client to reduce the number of consolidations required (parameter `n` which `10` by default, which might be too high to use Crossref).
