### ISSUE TITLE
Add segment sentences flag

### ISSUE THREAD

**Issue by reppertj** [kermitt2/grobid_client_python#36]
I needed to add a `--segment_sentences` flag to the CLI/process functions. It's a quick change that I've already made locally, LMK if you'd like a PR!

**Comment by kermitt2** [comment]
Hello @reppertj !
This is already in PR https://github.com/kermitt2/grobid_client_python/pull/32
I am waiting for feedback on the process reference list action to merge, but if you have a chance too to test the `--segmentSentences` option in the PR, thanks in advance (note: so far name of the CLI options mirrors the Grobid API paramters, thus rather `--segmentSentences` than `--segment_sentences` for consistency).

**Comment by reppertj** [comment]
Ah, sounds good! I'll give it a try, but the changes in the PR look simple enough!

**Comment by bnewbold** [comment]
Looks like this issue can be closed
