### ISSUE TITLE
How to add the `"segmentSentences": true` in the config file?

### ISSUE THREAD

**Issue by xegulon** [kermitt2/grobid_client_python#37]
Here is my `config.json`:

```json
{
    "grobid_server": "localhost",
    "grobid_port": "8070",
    "batch_size": 1000,
    "sleep_time": 5,
    "timeout": 60,
    "coordinates": [ "persName", "figure", "ref", "biblStruct", "formula", "s" ],
    "segmentSentences": true
}
```

I added at the end `"segmentSentences": true`, but even with that, I don't see the sentence segmentation in the TEIs. How to do that?

**Comment by kermitt2** [comment]
See https://github.com/kermitt2/grobid_client_python#usage-and-options
it's a command line argument.

**Comment by xegulon** [comment]
Thanks, but I don't use the command line, I use the client python object from within my python code. How to specify the sentence segmentation parameters that way?

**Comment by kermitt2** [comment]
Then it's a class method argument: 
https://github.com/kermitt2/grobid_client_python/blob/master/grobid_client/grobid_client.py#L460
https://github.com/kermitt2/grobid_client_python/blob/master/grobid_client/grobid_client.py#L107

**Comment by xegulon** [comment]
Thanks, so what I needed is:

```python
from grobid_client.grobid_client import GrobidClient

client = GrobidClient(config_path="config.json")
client.process("processFulltextDocument", "path/to/pdfs", segment_sentences=True, n=20)
```
