### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by venti07** [kermitt2/grobid_client_python#45]
File "/content/grobid_client_python/grobid_client/grobid_client.py", line 27, in <module>
    from .client import ApiClient
ImportError: attempted relative import with no known parent package

I am trying to use crobid with google colab.

How can I fix the error?

**Comment by LukasWallrich** [comment]
Just in case anyone searches in the future: I resolved this by starting python from a folder other than the one containing grobid_client ...
