### ISSUE TITLE
Empty xml file from the demo server

### ISSUE THREAD

**Issue by venti07** [kermitt2/grobid_client_python#46]
I have tried to process a pdf on the demo server. (cloud.science-miner.com/grobid)
I also get the corresponding xml file back. Unfortunately this is empty.

`
client = GrobidClient(config_path='/content/grobid_client_python/config.json')
client.process(service='processFulltextDocument',
               input_path='/content/input',
               output='/content/output',
               n=20,
               consolidate_citations=True, 
               tei_coordinates=False,
               force=True,
               verbose=True)
`

GROBID server is up and running
1 files to process in current batch

**Comment by lfoppiano** [comment]
@venti07 could you give some more information? is there any error? Could you run it with the option `--verbose` and share the result?

**Comment by venti07** [comment]
@lfoppiano thank you for your reply

I use this code in Google Colab:
https://github.com/venti07/share/blob/main/Grobid.ipynb

The code runs well and no errors are issued. Therefore I don't know what I can change.

With verbose i just get this information:
GROBID server is up and running
1 files to process in current batch

**Comment by lfoppiano** [comment]
@venti07 I tried with Colab and I have the same issue. I don't understand why. With a local deployment I have no problem to process the documents with grobid. 

The demo server is anyway not for testing large quantities of files. 
You could deploy a local version (perhaps via docker is the simplest way): https://grobid.readthedocs.io/en/latest/Grobid-docker/

**Comment by venti07** [comment]
Yes I am aware of it. Thanks for your help!
