### ISSUE TITLE
.pdf failed with error 500 , [BAD_INPUT_DATA] PDF to XML conversion failed with error code: 99

### ISSUE THREAD

**Issue by 92Komal** [kermitt2/grobid_client_python#55]
Hi, I am trying to run grobid to generate the .tei.xml file for bulk of pdf dataset.  I have installed GROBID  according to the [doc](https://grobid.readthedocs.io/en/latest/Grobid-service/) on my local machine (window 11 64 bit) and grobid server already connected and run [grobid_client_python](https://github.com/kermitt2/grobid_client_python). I have run the following command :

(grobid) C:\Users\krkom\Downloads\grobid_client_python-master\grobid_client_python-master> grobid_client --input PDF/10_files --output grobid_files/entailment --config config.json --consolidate_header --include_raw_citations --verbose processFulltextDocument.

when I tried to process a full text document there, I get a error code 99.:
[BAD_INPUT_DATA] PDF to XML conversion failed with error code: 99

I already refer [this](https://github.com/kermitt2/grobid/issues/166) issue but can't able to resolve 
and try with grobid latest version 0.7.1 and also 0.4.1.

Kindly help me resolve this issue, I would very much appreciate it! Thank you :)

**Comment by lfoppiano** [comment]
Hi, as stated in the [last comment](https://github.com/kermitt2/grobid/issues/166#issuecomment-698877091), and [in the documentation](https://grobid.readthedocs.io/en/latest/Troubleshooting/#windows-related-issues), Windows is not supported. 
You can use the docker image, please read carefully what described [here](https://grobid.readthedocs.io/en/latest/Grobid-docker/).
