### ISSUE TITLE
Grobid TEI coordinates

### ISSUE THREAD

**Issue by rabia0001** [kermitt2/grobid_client_python#56]
I am trying to get the page number for references. 

form = ProcessForm(
    segment_sentences="1",
    input_=File(file_name=pdf_file.name, payload=f, mime_type="application/pdf"), consolidate_citations="1",include_raw_citations="1",consolidate_header="1",tei_coordinates=True
)
r = process_fulltext_document.sync_detailed(client=client, multipart_data=form)

if r.is_success:
    article: Article = TEI.parse(r.content, figures=False)

When I do this I dont get the cooridnates ? is there a way I can get the coordinates or page number ?

**Comment by kermitt2** [comment]
Duplicates https://github.com/kermitt2/grobid/issues/982
