### ISSUE TITLE
GROBID server does not appear up and running 503

### ISSUE THREAD

**Issue by VincentOld** [kermitt2/grobid_client_python#70]
Hi, GROBID team！

Due to the use of **parallel processing** yesterday, I'm unable to use the GROBID API service now. 
Although I can use the web side, the API keeps reporting errors when calling the runtime:
**GROBID server does not appear up and running 503.** 
After checking your previous responses to similar issues, it seems that the service was blocked due to excessive parallel access. 
How should we solve this problem and when will it be unblocked?

Thanks！

**Comment by lfoppiano** [comment]
@VincentOld,  which grobid API do you mean?

**Comment by lfoppiano** [comment]
Closing the issue. Feel free to reopen and add some more details if the problem persists.
