### ISSUE TITLE
ImportError: cannot import name 'ApiClient' from 'grobid_client.client'

### ISSUE THREAD

**Issue by chozillla** [kermitt2/grobid_client_python#80]
`{
	"name": "ImportError",
	"message": "cannot import name 'ApiClient' from 'grobid_client.client' (c:\\Users\\cehs\\AppData\\Local\\anaconda3\\Lib\\site-packages\\grobid_client\\client.py)",
	"stack": "---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[11], line 1
----> 1 from grobid_client.grobid_client import GrobidClient
      3 client = GrobidClient(config_path=\"./config.json\")
      4 client.process(\"processFulltextDocument\", \"/Users/chemay/Documents/GitHub/EriksholmPublicationRAG/PublicERHreports\",output=\"./PublicERHReportsGROBID\", n=4)

File c:\\Users\\cehs\\AppData\\Local\\anaconda3\\Lib\\site-packages\\grobid_client\\grobid_client.py:27
     24 import requests
     25 import pathlib
---> 27 from .client import ApiClient
     30 class ServerUnavailableException(Exception):
     31     pass

ImportError: cannot import name 'ApiClient' from 'grobid_client.client' (c:\\Users\\cehs\\AppData\\Local\\anaconda3\\Lib\\site-packages\\grobid_client\\client.py)"
}` I am running a docker container and I got this error when I ran the client. I know 100% the docker is running, it is running on the local port. The issue seems to be with the client.

**Comment by Junyi-99** [comment]
same problem

**Comment by lfoppiano** [comment]
Which version did you install? 

```
pip list | grep grobid_client
```

**Comment by lfoppiano** [comment]
@Junyi-99 @chozillla feel free to reopen the issue if you still have the problem and you could provide more information.

**Comment by chozillla** [comment]
I am running grobid-client-python  0.0.8 and it works. Followed the build instructions on the GROBID website for docker.

**Comment by Junyi-99** [comment]
@lfoppiano Thanks for the reply, the problem was fixed by `pip install --upgrade --force-reinstall grobid-client`

**Comment by lfoppiano** [comment]
@Junyi-99 ref to #86 you meant `pip install --upgrade --force-reinstall grobid-client-python`?

**Comment by Junyi-99** [comment]
@lfoppiano No, not `grobid-client-python`, just `grobid-client`.

I'm not sure if the package kept the same name after all this time

**Comment by lfoppiano** [comment]
OK. That's weird. Anyway, to make the story short this repository is responsible only for the package `grobid-client-python`.
